
name: Clean HTML File

on:
  push:
    paths:
      - 'input-html/**'  # Trigger only when files in this folder change

jobs:
  clean-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean all HTML files in input-html
        run: |
          for file in input-html/*.html; do
            sed -i 's/\\"/"/g' "$file"
            sed -i 's/\\n//g' "$file"
          done

      - name: Upload cleaned HTML
        uses: actions/upload-artifact@v3
        with:
          name: cleaned-html
          path: input-html/
